import  {useState} from 'react'
import classes from "../../styles/MarkRegisterDashboard.module.css";
import MarkRegisterButtons from '../../components/Buttons/MarkRegisterButtons/MarkRegisterButtons'
import MarkRegisterTable from '../../components/Tables/MarkRegisterTable/MarkRegisterTable';

const markRegisterColumnArr = [
  { label: "S.No", value: "id" },
  { label: "Student Name", value: "studentname" },
  { label: "Student Id", value: "studentid" },
  {
    label: "Subjects",
    value: "subjects",
    subheadings: [
      { label: "Telugu", value: "telugu" },
      { label: "Maths", value: "maths" },
      { label: "Hindi", value: "hindi" },
      { label: "English", value: "english" },
      { label: "Science", value: "science" },
      { label: "Social", value: "social" },
    ],
  },
  { label: "Total Obtained Marks", value: "totalobtainedmarks" },
  { label: "Total Marks", value: "totalmarks" },
  { label: "Percentage", value: "percentage" },
  { label: "Result", value: "result" },
];

const studentMarkRegisterDetailsArr = [
  {
    id: 1,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 2,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 1,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 1,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 2,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 1,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 1,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 2,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 1,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 1,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 2,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 1,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 1,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 2,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 1,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 1,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 2,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
  {
    id: 1,
    studentname: "AAAA",
    studentid: 12345,
    subjects: {
      telugu: 90,
      maths: 85,
      hindi: 85,
      english: 80,
      science: 95,
      social: 88,
    },
    totalobtainedmarks: "523",
    totalmarks: "600",
    percentage: "95%",
    result: "Pass",
  },
]; 

export default function MarkRegister() {

const [studentMarkRegisterDetails, setstudentMarkRegisterDetails] = useState(studentMarkRegisterDetailsArr);

const [markRegisterColumn, setmarkRegisterColumn] = useState(markRegisterColumnArr);




  return (
    <div className={classes.salarydashboardgrid}>
      <MarkRegisterButtons />
      <MarkRegisterTable
        markRegisterColumn={markRegisterColumn}
        studentMarkRegisterDetails={studentMarkRegisterDetails}
      />
    </div>
  );
}
